server:
  port: 80
  address: localhost
  sessionTimeout: 30
#security:
#  user:
#    name: admin  
#    password: test

spring:
  freemarker:
    charset: UTF-8 
    content-type: text/html 
    suffix: .ftl
    
