server:
  port: 8010
#  address: 127.0.0.1
  sessionTimeout: 30
  context-path: /zkConsole
#security:
#  user:
#    name: admin  
#    password: test

spring:
  freemarker:
    charset: UTF-8 
    content-type: text/html 
    suffix: .ftl

# LOGGING
logging:
  path: .
  file: console.log
  level:
    com.lhl.zk: INFO
